---
title: Bestuur een interactief verkeerslicht met Python
hero_image: afbeeldingen / banner.png
description: Gebruik LED's, een knop en een zoemer om een ​​volledige reeks verkeerslichten met Python te programmeren
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmeren-0, computer gebruik-0
interests: "computergebruik"
technologies: "elektronica, computergebruik, python"
site_areas: ""
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: GPIO-componenten
  - 
    title: Verkeerslichten
  - 
    title: Verkeerslicht volgorde
