---
title: Bestuur een interactief verkeerslicht met Python
hero_image: images/banner.png
description: Gebruik LED's, een knop en een zoemer om een ​​volledige reeks verkeerslichten met Python te programmeren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-1, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introductie
- title: Wat heb je nodig
- title: GPIO-componenten
- title: Verkeerslichten
- title: Verkeerslicht volgorde