---
title: Bestuur een interactief verkeerslicht met Python
hero_image: images/banner.png
description: Gebruik LED's, een knop en een zoemer om een ​​volledige reeks verkeerslichten met Python te programmeren
listed: false
copyedit: false
version: 4
last_tested: 2018-11-21
steps:
  - 
    title: Introductie
  - 
    title: Verbind de componenten
  - 
    title: Bedien de LED's en de knop
  - 
    title: Verkeerslichten
  - 
    title: Verkeerslicht volgorde
