---
title: Bestuur een interactief verkeerslicht met Python
hero_image: images/banner.png
description: Gebruik LED's, een knop en een zoemer om een ​​volledige reeks verkeerslichten met Python te programmeren
listed: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introductie
  - 
    title: Wat heb je nodig
  - 
    title: GPIO-componenten
  - 
    title: Verkeerslichten
  - 
    title: Verkeerslicht volgorde
