title: Control an Interactive Traffic Lights Sequence with Python
hero_image: images/banner.png
description: Use LEDs, a button and a buzzer to program a full traffic lights sequence with Python
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: GPIO components
  - title: Traffic lights
  - title: Traffic lights sequence
