---
title: Pythonでインタラクティブなトラフィックライトシーケンスを制御する
hero_image: images/banner.png
description: LED、ボタン、ブザーを使用して、Pythonで全交通信号のシーケンスをプログラムする
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: GPIOコンポーネント
  - 
    title: 交通信号灯
  - 
    title: 交通信号のシーケンス
