---
title: Pythonでインタラクティブなトラフィックライトシーケンスを制御する
hero_image: images / banner.png
description: LED、ボタン、ブザーを使用して、Pythonで全交通信号のシーケンスをプログラムする
listed: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: GPIOコンポーネント
  - 
    title: 交通信号灯
  - 
    title: 交通信号のシーケンス
