---
title: Pythonでインタラクティブなトラフィックライトシーケンスを制御する
hero_image: images / banner.png
description: LED、ボタン、ブザーを使用して、Pythonで全交通信号のシーケンスをプログラムする
theme: 赤
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: プログラミング-0、phys-comp-0
interests: "物理計算"
technologies: "エレクトロニクス、物理計算機、Python"
site_areas: ""
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: GPIOコンポーネント
  - 
    title: 交通信号灯
  - 
    title: 交通信号のシーケンス
