---
title: Interactive Traffic Lights with Python
hero_image: изображения / banner.png
description: Use LEDs, a button and a buzzer to program an interactive traffic lights sequence with Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Въведение
  - 
    title: Connect the components
  - 
    title: Control the LEDs and button
  - 
    title: Traffic lights
  - 
    title: Traffic lights sequence
