---
title: کنترل ترتیب چراغ راهنمایی با پایتون
hero_image: images/banner.png
description: از LEDها، یک دکمه و یک زنگ برای برنامه‌ریزی یک چراغ راهنمایی با پایتون، استفاده کنید
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0، phys-comp-0
interests: ''
technologies: الکترونیک، محاسبات فیزیکی، پایتون
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: مقدمه
  - 
    title: آنچه شما نیاز دارید
  - 
    title: اجزای GPIO
  - 
    title: چراغ راهنمایی
  - 
    title: ترتیب چراغ راهنمایی
