---
title: Steuere einen interaktiven Verkehrsampel-Ablauf mit Python
hero_image: images/banner.png
description: Verwende LEDs, einen Taster und einen Summer, um einen vollständigen Ampel-Ablauf mit Python zu programmieren
listed: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: GPIO-Komponenten
  - 
    title: Verkehrs-Ampel
  - 
    title: Verkehrsampel-Ablauf
