---
title: Steuern Sie eine interaktive Ampel Sequenz mit Python
hero_image: Bilder / Banner.png
description: Verwenden Sie LEDs, eine Taste und einen Summer, um eine vollständige Ampelkette mit Python zu programmieren
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Elektronik, physikalisches Rechnen, Python"
site_areas: ""
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: GPIO-Komponenten
  - 
    title: Ampeln
  - 
    title: Ampel Sequenz
