---
title: Steuere einen interaktiven Verkehrsampel-Ablauf mit Python
hero_image: images/banner.png
description: Verwende LEDs, einen Taster und einen Summer, um einen vollständigen Ampel-Ablauf mit Python zu programmieren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-1, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps: 
-
title: Einleitung
-
title: Was du brauchen wirst
-
title: GPIO-Komponenten
-
title: Verkehrs-Ampel
-
title: Verkehrsampel-Ablauf