---
title: Steuere einen interaktiven Verkehrsampel-Ablauf mit Python
hero_image: images/banner.png
description: Verwende LEDs, einen Taster und einen Summer, um einen vollständigen Ampel-Ablauf mit Python zu programmieren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas: ""
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: GPIO-Komponenten
  - 
    title: Verkehrs-Ampel
  - 
    title: Verkehrsampel-Ablauf
