---
title: Steuere eine interaktive Verkehrsampel-Sequenz mit Python
hero_image: images/banner.png
description: Verwende LEDs, eine Taste und einen Summer, um eine vollständige Ampel-Sequenz mit Python zu programmieren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "electronics, physical computing, python"
site_areas: ""
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: GPIO-Komponenten
  - 
    title: Verkehrs-Ampel
  - 
    title: Verkehrsampel-Sequenz
