---
title: Interaktív közlekedési lámpa Pythonban
hero_image: images/banner.png
description: LED-ek, egy gomb és egy berregő segítségével programozz egy interaktív közlekedési lámpát Pythonban
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Kösd össze a komponenseket
  - 
    title: Vezéreld a LED-eket és a gombot
  - 
    title: Közlekedési lámpa
  - 
    title: A közlekedési lámpa ciklusa
