---
title: Az interaktív közlekedési lámpák szekvenciájának vezérlése a Python segítségével
hero_image: images / banner.png
description: Használjon LED-eket, egy gombot és egy zümmögőt, hogy programozhasson egy teljes forgalomjelző sorozatot Python-val
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programozás-0, fizikai-comp-0
interests: "fizikai számítástechnika"
technologies: "elektronika, fizikai számítástechnika, python"
site_areas: ""
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: GPIO komponensek
  - 
    title: Közlekedési lámpák
  - 
    title: A közlekedési lámpa sorrendje
