---
title: Contrôler une séquence de feux de circulation interactive avec Python
hero_image: images/banner.png
description: Utilisez des DELs, un bouton et un avertisseur sonore pour programmer
  une séquence de feux de circulation complète avec Python
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-1, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Ce dont vous aurez besoin
- title: Composants GPIO
- title: Feux de circulation
  completion: internal
- title: Séquence de feux de circulation
