---
title: Feux de circulation interactifs avec Python
hero_image: images/banner.png
description: Utilise des LED, un bouton et un buzzer pour programmer une séquence interactive de feux de signalisation avec Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Connecter les composants
  - 
    title: Contrôler les LED et le bouton
  - 
    title: Feux de circulation
  - 
    title: Séquence de feux de circulation
