---
title: Interactive Traffic Lights with Python
hero_image: images/banner.png
description: Use LEDs, a button and a buzzer to program an interactive traffic lights sequence with Python
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Connect the components
  - 
    title: Control the LEDs and button
  - 
    title: Traffic lights
  - 
    title: Traffic lights sequence
