---
title: Contrôler une séquence de feux de circulation interactive avec Python
hero_image: images / banner.png
description: Utilisez des voyants, un bouton et un buzzer pour programmer une séquence de feux de circulation complète avec Python
theme: rouge
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programmation-0, phys-comp-0
interests: "informatique physique"
technologies: "électronique, informatique physique, python"
site_areas: ""
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Composants GPIO
  - 
    title: Feux de circulation
  - 
    title: Séquence de feux de circulation
