---
title: Controlla una sequenza di semafori interattivi con Python
hero_image: images / banner.png
description: Usa LED, un pulsante e un cicalino per programmare una sequenza completa di semafori con Python
listed: false
copyedit: false
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Componenti GPIO
  - 
    title: Semafori
  - 
    title: Sequenza dei semafori
