---
title: Semaforo interattivo con Python
hero_image: images/banner.png
description: Usa i LED, un pulsante e un cicalino per programmare la sequenza delle luci di un semaforo con Python
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduzione
  - 
    title: Collega i componenti
  - 
    title: Controlla i LED ed il pulsante
  - 
    title: Semafori
  - 
    title: Sequenza del semaforo
