---
title: Controlla una sequenza di semafori interattivi con Python
hero_image: images/banner.png
description: Usa LED, un pulsante e un cicalino per programmare una sequenza completa
  di semafori con Python
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-1, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: introduzione
- title: Di cosa avrai bisogno
- title: Componenti GPIO
- title: Semafori
- title: Sequenza dei semafori
